### ISSUE TITLE
return () => target.concat(that.callQueue);

### ISSUE THREAD

**Issue by albes** [briankircho/mongoose-schema-extend#40]
New version cause an error here:
....../node_modules/mongoose-schema-extend/index.js:28
        return () => target.concat(that.callQueue);
                ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

................

**Comment by sieira** [comment]
Can you provide a use case?

**Comment by albes** [comment]
Sorry but i don't know if i can help you... this is the log
.../node_modules/mongoose-schema-extend/index.js:28
        return () => target.concat(that.callQueue);
                ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (..../app/models/GenericDeviceChannel.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /...../server.js:55:29
    at Array.forEach (native)
    at Object.<anonymous> (../server.js:54:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)


How can i help you?

**Comment by albes** [comment]
I have solved it installing the 0.2.0 version. this error is in the 0.2.1 version

**Comment by sieira** [comment]
It looks like the version of node you're using does not support lambda expressions.

Can you test this in your node commandline?

`(() => console.log("Hello World!"))();`

**Comment by albes** [comment]
Ah ok! It's not working... yes probably the problem is my node version, I'm using 0.10.40.

**Comment by sieira** [comment]
Then you need to upgrade your node, or downgrade this library. The new version allows pre middleware to work, if you use it, then I',m afraid you need to upgrade node

**Comment by albes** [comment]
Thank you very much for your fast support!!
Regards
