### ISSUE TITLE
replacing clone by deepCopy does not fix clone implementation

### ISSUE THREAD

**Issue by donnut** [briankircho/mongoose-schema-extend#5]
In version 0.1.2. the fix in lines 14-21 were removed. This fix seems to be necessary, even with owl-deepcopy. Without the fix I get the following error:

    TypeError: Cannot read property 'numAsyncPres' of undefined
      at model.module.exports._lazySetupHooks (/home/donnut/dev/js/node_modules/mongoose/node_modules/hooks/hooks.js:149:49)
      at model.module.exports.pre (/home/donnut/dev/js/node_modules/mongoose/node_modules/hooks/hooks.js:113:10)
      at model.Document._doQueue (/home/donnut/dev/js/node_modules/mongoose/lib/document.js:1256:21)
      at model._registerHooks (/home/donnut/dev/js/node_modules/mongoose/lib/document.js:1231:8)
      at model.registerHooks [as _registerHooks] (/home/donnut/dev/js/node_modules/mongoose/lib/model.js:704:37)
      at model.Document (/home/donnut/dev/js/node_modules/mongoose/lib/document.js:69:8)
      at model.Model (/home/donnut/dev/js/node_modules/mongoose/lib/model.js:34:12)
      at new model (/home/donnut/dev/js/node_modules/mongoose/lib/model.js:1668:11)

when instantiating a new mongoose.model. With the fix in place, all works fine.

**Comment by sieira** [comment]
Looks like it is fixed
