### ISSUE TITLE
Schema Inheritance Error (TypeError: Cannot read property '0' of undefined)

### ISSUE THREAD

**Issue by xulong3370** [briankircho/mongoose-schema-extend#56]
When I try schema inheritance :
```
var mongoose = require('mongoose'),
    extend = require('mongoose-schema-extend');
var Schema = mongoose.Schema;

var PersonSchema = new Schema({
    name : String
}, { collection : 'users' });

var EmployeeSchema = PersonSchema.extend({
    department : String
});

var Person = mongoose.model('Person', PersonSchema),
    Employee = mongoose.model('Employee', EmployeeSchema);
```

I get the following error:

> "E:\Program Files\JetBrains\WebStorm 2017.1.1\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" D:\Users\test_extend\test.js
> D:\Users\test_extend\node_modules\mongoose\lib\services\model\applyHooks.js:34
>     if (pair[0] !== 'pre' && pair[0] !== 'post' && pair[0] !== 'on') {
>             ^
> 
> TypeError: Cannot read property '0' of undefined
>     at applyHooks (D:\Users\test_extend\node_modules\mongoose\lib\services\model\applyHooks.js:34:13)
>     at Function.compile (D:\Users\test_extend\node_modules\mongoose\lib\model.js:3636:3)
>     at Mongoose.model (D:\Users\test_extend\node_modules\mongoose\lib\index.js:417:22)
>     at Object.<anonymous> (D:\Users\test_extend\test.js:17:25)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:393:7)
>     at startup (bootstrap_node.js:150:9)
>     at bootstrap_node.js:508:3
> 
> Process finished with exit code 1

It looks like the following code cause the error:
```
var EmployeeSchema = PersonSchema.extend({
    department : String
});

 Employee = mongoose.model('Employee', EmployeeSchema);`
```

**Comment by Climax777** [comment]
Same for me. Upgraded from mongoose 4.9.1 to 4.9.8

**Comment by Climax777** [comment]
@xulong3370 have you been able to find a workaround?

**Comment by xulong3370** [comment]
@Climax777 not resolve so far....

**Comment by mwlvandermaat** [comment]
Still no workaround?

**Comment by Climax777** [comment]
@mwlvandermaat not that I know of

**Comment by pcemma** [comment]
Is there a solution for this issue?

**Comment by sde-turner** [comment]
I confirm I am facing a similar issue.

For what it's worth the last working Mongoose version I can find with 0.2.2 of mongooses-schema-extend that is working is 4.9.7

**Comment by amorimdub** [comment]
I got the same error.

My mistake was: I was initializing the child's model before father's model.

Please, double check which one is load first.

**Comment by pcemma** [comment]
Nope. It's still not working. I'm sure that parent model is initialized before children one.

**Comment by hoangnguyenba** [comment]
Still not fixed :(

**Comment by InsomniakDev** [comment]
almost one year later still not resolved :'(
