### ISSUE TITLE
Method Map.prototype.has called on incompatible receiver

### ISSUE THREAD

**Issue by Hyperblaster** [briankircho/mongoose-schema-extend#59]
Just Updated mongoose from 5.0.16 to 5.1.7 and now encounter this error. 
Rolling back to 5.0.16, everything works fine. Is mongoose-schema-extend not valid with the later versions of mongoose?

```
TypeError: Method Map.prototype.has called on incompatible receiver [object Map]
    at Clone.has (<anonymous>)
    at get (/node_modules/kareem/index.js:418:11)
    at Clone.Kareem.pre (/node_modules/kareem/index.js:350:16)
    at Clone.Schema.pre (/node_modules/mongoose/lib/schema.js:1135:20)
    at Schema.extend (/node_modules/mongoose-schema-extend/index.js:92:15)
```

**Comment by techitesh** [comment]
Facing Same issue on mongoose version  "^5.1.7" any solution???

**Comment by kennylmay** [comment]
I also face the same problem. I have narrowed it down to 5.1.4  of mongoose works to 5.1.5 doesn't.

**Comment by techitesh** [comment]
I created By Own Plugin and Resolved the Issue

**Comment by bdsomer** [comment]
@techitesh Could you please explain your solution?

**Comment by kennylmay** [comment]
@bdsomer I forked it and fixed this problem I believe. Give it a try and see if it works for you https://github.com/kennylmay/mongoose-schema-extend

**Comment by bdsomer** [comment]
@kennylmay I would make a PR to this repo! I know the developers aren't active but just in case they come back.

**Comment by dsc8x** [comment]
@Hyperblaster note that you actually don't really need this lib anymore, as this is now built into mongoose: https://mongoosejs.com/docs/api.html#model_Model.discriminator

**Comment by Hyperblaster** [comment]
@epegzz Know of an upgrade tutorial at all out there?
